<?php
    $labels = array();
    $labels['in'] = 'In';
    $labels['and'] = 'Und';
    $labels['or'] = 'Oder';
    $labels['not'] = 'Nicht';
    $labels['where'] = 'Wo';
    $labels['exclude'] = 'ausschließen';
    $labels['andsubfolders'] = 'mit Unterordnern';
    $labels['allfolders'] = 'Alle Ordner';
    $labels['advancedsearch'] = 'Erweiterte Suche';
    $labels['label_display_options'] = 'Anzeigeoptionen';
    $labels['mailbox_headers_in_results'] = 'Ordnername als Reihe anzeigen';
    $labels['mailbox_info_in_results'] = 'Ordnername als Kolonne anzeigen';
    $labels['display_in_messagemenu'] = 'im Nachrichtenmenü anzeigen';
    $labels['display_in_toolbar'] = 'als Button in der Toolbar anzeigen';
    $labels['show_advanced_search'] = 'Erweiterte Suche';