<?php
    $labels = array();
    $labels['in'] = 'In';
    $labels['and'] = 'And';
    $labels['or'] = 'Or';
    $labels['not'] = 'Not';
    $labels['where'] = 'Where';
    $labels['exclude'] = 'Exclude';
    $labels['andsubfolders'] = 'and subfolders';
    $labels['allfolders'] = 'All Folders';
    $labels['advancedsearch'] = 'Advanced search';
    $labels['label_display_options'] = 'Display options in search results';
    $labels['mailbox_headers_in_results'] = 'Show mailbox title as row';
    $labels['mailbox_info_in_results'] = 'Show mailbox title as column';
    $labels['display_in_messagemenu'] = 'in message menu';
    $labels['display_in_toolbar'] = 'as button in toolbar';
    $labels['show_advanced_search'] = 'Show advanced search';